on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout me"
        uses: actions/checkout@v2
        with:
          path: ./pushyou

      - name: "checkout you"
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository_owner }}/pullme"
          token: ${{ secrets.PUSH_PULL }}
          path: ./pullme

      - name: "generator"
        run: echo "across the universe" > ./pullme/hello.txt

      - name: "commander"
        run: ls -lA ./pullme; cat ./pullme/hello.txt

      - name: "save hello"
        run: |
          cd ./pullme
          git config --local user.name "${{ github.repository_owner }}"
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git add hello.txt
          git commit -m "save hello"
          git status

      - name: "check config"
        run: |
          cd ./pullme
          git config -l

      - name: "push you"
        run: |
          cd ./pullme
          git push origin main
