on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout me"
        uses: actions/checkout@v2
        with:
          path: ./pushyou

      - name: "checkout you"
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository_owner }}/pullme"
          token: ${{ secrets.PUSH_PULL }}
          path: ./pullme

      - name: "generator"
        run: echo "from the other side" > ./pullme/hello.txt

      - name: "commander"
        run: ls -lA ./pullme; cat ./pullme/hello.txt
